# Generated by Django 4.1 on 2022-10-23 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_task_is_finished_alter_task_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='is_finished',
        ),
    ]
