# Generated by Django 4.1 on 2022-09-29 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0003_task_is_finished_alter_task_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='is_finished',
        ),
    ]
